source "https://rubygems.org"
gem 'sinatra'
gem 'pry'
gem 'sqlite3'
gem 'shotgun'
gem 'rake'
gem 'rack'
gem 'activerecord', '~> 5.0', '>= 5.0.0.1' 
gem 'sinatra-activerecord'
gem 'thin'
gem 'tux'
gem 'dotenv'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'require_all'